### ISSUE TITLE
Error with Git

### ISSUE THREAD

**Issue by almarvb** [EmpireMediaScience/A1111-Web-UI-Installer#10]
![image](https://user-images.githubusercontent.com/38662202/208960264-bc595d70-c332-4198-a403-576ea7fd2be4.png)

Hi. Got this error message during the install process.

**Comment by Mozoloa** [comment]
I believe we've sorted this on reddit ? The solution is :
Install [git ](https://github.com/git-for-windows/git/releases/download/v2.39.0.windows.2/Git-2.39.0.2-64-bit.exe) manually and check to add it to path during the install
![image](https://user-images.githubusercontent.com/20817233/209005206-80bd9b9c-9c06-4e20-a972-840a812dbab3.png)

Then relaunch the installer & uncheck git in the first screen, then install normally

**Comment by firecz** [comment]
Installing stuff manually kinda defies the purpose of the automatic installer though...

**Comment by Mozoloa** [comment]
That's a workaround until I find the bug, but I had no other info that git wasn't installed in path. My installer normally does it and it works in 99% of the cases

**Comment by Mozoloa** [comment]
https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/releases/tag/V1.5-beta0 the new beta release should completely fix this kind of issues

**Comment by SubZero7748** [comment]
I encountered the bug on the v1.6.1 version. powershell not recognizing git on the first attempt (after running the web ui installer for the very first time). relaunching the web ui installer fixed the problem, git is now recognized and is downloading repo's.
