### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by nativenoble** [EmpireMediaScience/A1111-Web-UI-Installer#11]
Hi there, 

i get this error when i try to install:

Dumping PowerShell invoke log ...
--> Found PowerShell path: C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe
--> PowerShell Script Execution Result Code: 574
--> PowerShell Script Execution log: 
ERROR: Der Typ kann nicht hinzugefügt werden. Die Definition neuer Typen wird in diesem Sprachmodus nicht unterstützt.
MSI (c) (68!A0) [10:55:20:328]: PROPERTY CHANGE: Adding POWERSHELL_EXECUTION_LOG property. Its value is 'ERROR: Der Typ kann nicht hinzugefügt werden. Die Definition neuer Typen wird in diesem Sprachmodus nicht unterstützt.'.
CustomAction dlModel returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 10:55:20: dlModel. Return value 3.
MSI (c) (68:00) [10:55:20:328]: Doing action: FatalError
Action start 10:55:20: FatalError.
Action ended 10:55:24: FatalError. Return value 1.
MSI (c) (68:00) [10:55:24:890]: Doing action: AI_SHOW_LOG
Action start 10:55:24: AI_SHOW_LOG.
MSI (c) (68:F0) [10:55:24:896]: Invoking remote custom action. DLL: C:\Users\#####\AppData\Local\Temp\MSI954E.tmp, Entrypoint: LaunchLogFile
Action ended 10:55:25: AI_SHOW_LOG. Return value 1.
MSI (c) (68:00) [10:55:25:077]: Doing action: FatalError
Action start 10:55:25: FatalError.
Action ended 10:55:25: FatalError. Return value 2.
MSI (c) (68:00) [10:55:25:077]: Note: 1: 2205 2:  3: Environment 
MSI (c) (68:00) [10:55:25:077]: Note: 1: 2228 2:  3: Environment 4: SELECT `Environment`,`Component_` FROM `Environment` 
MSI (c) (68:00) [10:55:25:122]: Destroying RemoteAPI object.
MSI (c) (68:1C) [10:55:25:123]: Custom Action Manager thread ending.
=== Verbose logging stopped: 22.12.2022  10:55:25 ===

**Comment by Mozoloa** [comment]
It looks like your computer is preventing your from running powershell scripts, that's pretty odd. Try to install without downloading the model ? It looks like it failed there

**Comment by Mozoloa** [comment]
Issue is stale, re open if you still have the problem and can answer my question
