### ISSUE TITLE
"A111 Web UI Autoinstaller requires an active Internet connection for installation."

### ISSUE THREAD

**Issue by robdhayes** [EmpireMediaScience/A1111-Web-UI-Installer#13]
"Please check your network configuration and proxy settings."

I have Windows Firewall disabled, no antivirus, and use a bunch of other self-hosted apps.

Any idea what may be causing this?

I can email the log somewhere, but I'd rather not upload it here in case it contains vulnerable info.

**Comment by Mozoloa** [comment]
I had this problem on another installer, and another computer, where the network was kind of broken, showing "no internet" connexion, altho internet was working, but I've never found the solution, is this your case ?

**Comment by robdhayes** [comment]
This was indeed the issue, thanks.

ipconfig /release
ipconfig /renew
Restart

Resolved.

**Comment by Mozoloa** [comment]
Glad to know !
