### ISSUE TITLE
Launcher showing old graphics card in footer

### ISSUE THREAD

**Issue by robdhayes** [EmpireMediaScience/A1111-Web-UI-Installer#14]
![old-card](https://user-images.githubusercontent.com/12415965/209259560-f5174c8a-f658-490c-9b45-d70c9f1fc4df.png)

I have not had a GTX 770 installed in many months.  I now have an RTX 3050, so it's unclear where it is getting that old data.

The Web UI seems to work as expected, though I have only been using it a short while.  I suspect that perhaps it would optimize better if it knew my proper graphics card.

**Comment by Mozoloa** [comment]
Haha that's very odd indeed, it's getting the info from the registry.
Can you tell me what entering this in powershell gives you ?
`(Get-ItemProperty -Path "HKLM:\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0*" -Name "HardwareInformation.AdapterString", "HardwareInformation.qwMemorySize" -Exclude PSPath -ErrorAction SilentlyContinue)`

**Comment by Mozoloa** [comment]
Try to update your graphics drivers, i'll close as the issue is stale, reopen if the issue persists

**Comment by g4ggia** [comment]
I'm experiencing this same issue -- an old graphics card that's no longer installed is showing on the launcher. The issue persists after I updated the launcher (non-clean installation). I hope this isn't affecting SD performance by instructing Automatic1111 that my GPU is worse than it is in reality!

**Comment by Mozoloa** [comment]
No it's just for show honestly it doesn't affect anything
