### ISSUE TITLE
Having a different python version at the start breaks the installation

### ISSUE THREAD

**Issue by rexelbartolome** [EmpireMediaScience/A1111-Web-UI-Installer#15]
Say if a person has python 3.11 for some reason, the installer wouldn't realize that, nor give a warning about it. If this is meant to be a user friendly installation, i think it should at least give some warning for that

**Comment by Mozoloa** [comment]
The installer will install 3.10, it can totally be installed with 3.11 on the same machine, it even grabs the installation location to use it for the webui only, how does that break the installation ?

**Comment by rexelbartolome** [comment]
my bad, that was a different installation method i tried with my friend. When we tested this one out, it came out fine, but we had problems with installing torch and torchvision and we managed to fix it with updating nvidia drivers and cuda itself. Maybe add an option to check for those instead? But ofc, torch is more related to webui itself, rather than this repo

**Comment by Mozoloa** [comment]
I don't know yet how to do this and you're right it's not really related to the installer, anyway the readme has a warning to update Nvidia Drivers, I'll keep that in mind
