### ISSUE TITLE
Some error related to python after installation

### ISSUE THREAD

**Issue by Loner29** [EmpireMediaScience/A1111-Web-UI-Installer#16]
_Got a problem after download the Installer and having installed it, now running the Installer throws me this error:

https://i.imgur.com/a90rtun.png

Any ideas what could be the culprit? I've installed the dependencies beforehand and tried to install it on my main and a second drive._

edit: Maybe i should have read what the error actually says, sorry not in the coding language business. I added "--skip-torch-cuda-test" as a startup command and now it's doing something again. Will report back once it's done.

edit2: I got the installer to install most of the stuff now presumingly but now when it comes to actually pulling the stable-diffusion repository i'm now stuck with this error: https://i.imgur.com/u9bFa0p.png

Any idea here?

**Comment by Mozoloa** [comment]
Your installation seems broken, but I believe this is unrelated to the installer, check the warning at the top of the readme

**Comment by Mozoloa** [comment]
Try deleting venv
