### ISSUE TITLE
Colab ? 

### ISSUE THREAD

**Issue by freeload101** [EmpireMediaScience/A1111-Web-UI-Installer#17]
Looks like you did a fair amount of work want to colab with this ? I can screen share and  we can share ideas etc. I was the one that posted on UD :P 

**Is your feature request related to a problem? Please describe.**
Nope mainly that the A1111 installer is a installer so its like you wrote a installer for a installer ? is this based off a non free MSI tool ? https://www.advancedinstaller.com/ ? I would have gone with pure ps1 or NSIS (Nullsoft Scriptable Install System) ?
 
**Describe the solution you'd like**
replace A1111 crazy install scripts into single ps1 script using super lightweight git portable and python nuget that works in it's own portable env without  that wonky package manager Anaconda or anything ...

Python: 
https://github.com/freeload101/SCRIPTS/blob/ada6370eb82b33b8bfe94b8dafa72a0d3719d08f/Windows_Powershell_ps/AUTOMATIC1111_REAL_ONECLICK_INSTALL_Portable.ps1#L129

Git: https://github.com/freeload101/SCRIPTS/blob/ada6370eb82b33b8bfe94b8dafa72a0d3719d08f/Windows_Powershell_ps/AUTOMATIC1111_REAL_ONECLICK_INSTALL_Portable.ps1#L105 
 
Pure powershell UI for Android testing Suite ( mostly portable) :
https://github.com/freeload101/Java-Android-Magisk-Burp-Objection-Root-Emulator-Easy

some random to-dos ill never do unless you want me to add them to your project or somebody ask for it :

* command line ? --xformers --deepdanbooru --disable-safe-unpickle --listen --theme dark
* add decent models via areia2c magnet links?
* pull and ask if you want to run cmdr2
* warn about existing python env ...
* check for existing python env
* check for anaconda BS
* delete files like:
c:\users\administrator\appdata\local\pip
c:\users\administrator\appdata\roaming\python\
* add Invoke AI ?
git clone Invoke AI
copy environments-and-requirements\requirements-win-colab-cuda.txt requirements.txt
# start SD webui first so it fixes depends ...
pip install --prefer-binary -r requirements.txt
python scripts\invoke.py --web

**Comment by Mozoloa** [comment]
That's a lot of information at the same time, I'm not sure I get them all. My installer already just installs git & python then clone the repo. Granted this could be done via powershell to get rid of the advanced installer stuff, I'll look into it

**Comment by freeload101** [comment]
> That's a lot of information at the same time, I'm not sure I get them all. My installer already just installs git & python then clone the repo. Granted this could be done via powershell to get rid of the advanced installer stuff, I'll look into it

that's what I'm saying I kind of looked around are you French?  English as a second language?  Feel free to se something up if you want to chat. I'm basically talking about making it all Powsershell and removing the need for git and Python to be installed at all.. I currently don't have git or python installed and I have 2 versions 1.5 and 2.X both running with their own independent git and python all contained in their own folder ( mostly )

Book a call and see my availability:

https://bit.ly/BookMcCurdy

**Comment by Mozoloa** [comment]
I don't think I'll have time for a call any time soon, but I'll look into making an portable env to run all of this asap

**Comment by Mozoloa** [comment]
So you could change GIT= and PYTHON= to some folder next to the launcher, without having them installed, what do you mean by "mostly" ? Are there still dependencies needed ? that would be a bummer as this solutions seemed ideal

**Comment by Mozoloa** [comment]
working on it in [this branch](https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/tree/Making-Py-and-Git-Portable)

**Comment by Mozoloa** [comment]
First go at it https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/releases/tag/V1.5-beta0

**Comment by Mozoloa** [comment]
I just realised you already had an implementation of this, I'll have a look

**Comment by Mozoloa** [comment]
I'll close this issue as this should probably be in Discussions instead, if you're still interested, don't hesitate to create a post there and concentrate on Automatic1111 webui, the rest is unrelated
