### ISSUE TITLE
[Bug]: Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by MrThista** [EmpireMediaScience/A1111-Web-UI-Installer#18]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part, and this problem occured before I pressed "Launch WebUI"

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

Windows Defender flasgs as having a virus: 

Trojan:Win32/Wacatac.B!ml

### Steps to reproduce the problem

1. download
2. try to run application
3. gets blocked

### What should have happened?

opened the exe.

### Version of the Installer/Launcher where the problem happens

v1.4.0

**Comment by Mozoloa** [comment]
I have no idea where that comes from honestly, I'll try updating my Advanced Installer Asap, and maybe change the installer to a ps1 script

**Comment by Klendat** [comment]
Same issue. Chrome is even blocking the download of the release.

**Comment by MrThista** [comment]
yeah, i had to install firefox to even get it to download,

**Comment by Mozoloa** [comment]
I've never got around to not get warnings in my installers, as I have no idea how the signing stuff works around all this. I'll probably make a little Winforms UI script instead, but this could make it harder to install for beginners

**Comment by steve709** [comment]
Here are a few more details I have observed when downloading with Microsoft Edge.

**Windows 10**
- Windows Defender immediately deletes 1.4.0
- 1.3.4 is apparently fine and is not deleted

**Windows 11**
- 1.4.0 is apparently fine and is not deleted. Windows Defender does not flag it.

**Comment by Mozoloa** [comment]
Maybe try with the new release ? not sure this will change something but I signed the installer

**Comment by steve709** [comment]
Yes, 1.4.1 works for me in Windows 10. Thanks!

**Comment by Mozoloa** [comment]
@MrThista and @Klendat 
Tells us what's up

**Comment by Klendat** [comment]
1.4.1 works for me. No red flags.

**Comment by Mozoloa** [comment]
good
