### ISSUE TITLE
Provide PowerShell install script along with the exe.

### ISSUE THREAD

**Issue by MrThista** [EmpireMediaScience/A1111-Web-UI-Installer#19]
Saves the anti virus flagging it

**Comment by Mozoloa** [comment]
Do you mean to create a powershell installer ? I've been thinking about it, I might do it, would simplify a lot of stuff

**Comment by MrThista** [comment]
yeah I think it would be useful, for me anyway haha.

**Comment by Mozoloa** [comment]
Discussed in this issue : #17
