### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by Northloop** [EmpireMediaScience/A1111-Web-UI-Installer#20]
**Is your feature request related to a problem? Please describe.**
Working with the newer 4090 has been a bit of a pain to install automatic 1111's webui while getting good results. 

**Describe the solution you'd like**
Having extended options that install xformers and CUDA files based on our graphics card would be nice. 

**Describe alternatives you've considered**
There's a newer pytorch ccu117 and CUDA 118 files to install that increases iterations per second for RTX 4090 users along with a different version of xformers.

**Additional context**
Having additional install options for 4090 users would be awesome, I love that you've created this installer.

**Comment by Mozoloa** [comment]
Unfortunately I can't take responsibility for drivers & cuda installs as well, as git and python have their fair share of bugs already, and I somehow have to provide support for it lmao. Soon the installer is just going to be a powershell script so people will be able to contribute more easily and maybe PR this kind of request
