### ISSUE TITLE
[Bug]: Launcher won't find the installed Python.

### ISSUE THREAD

**Issue by WhiteX** [EmpireMediaScience/A1111-Web-UI-Installer#21]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part, and this problem occured before I pressed "Launch WebUI"

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

Great work with the launcher! I have a small problem with it though.

The launcher check's for Python's executable in the windows registry, but for some reason I don't have it there... not exactly sure why. I have the path to the exe in the windows environment variables (added it manually), so it should simply work without finding the path to it.

Anyway, I added the path to Python manually to the script, that fixes the issue.
`$pyPath = "C:\Python310\python.exe"`

### Steps to reproduce the problem

1. Launcher Launches sucessfully.
2. But won't launch A1111's web UI
3. Is looking for Python.
4. Adding the Path to Python manually to the launcher, fixes the issue (obviously not a solution, just for the sake of testing).

### What should have happened?

Finding Python.

### Version of the Installer/Launcher where the problem happens

Latest (1.4.1)

**Comment by Mozoloa** [comment]
What does `Get-ItemProperty -path "hkcu:\Software\Python\PythonCore\3.10\InstallPath"` gives you in powershell

**Comment by WhiteX** [comment]
Python 3.10 not found... And stops.

**Comment by WhiteX** [comment]
I mean checked the key manually and it's empty. I don't even have the
Python subfolder in that location in the registry. I'll run the code when I
get back to my desk.

**Comment by odzeno** [comment]
I have the exact same problem, the reg key isn't there, here is what I get running it:

> Get-ItemProperty : Cannot find path 'HKCU:\Software\Python\PythonCore\3.10\InstallPath' because it does not exist.
At line:1 char:1
>+ Get-ItemProperty -path "hkcu:\Software\Python\PythonCore\3.10\Install ...
>+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    + CategoryInfo          : ObjectNotFound: (HKCU:\Software\....10\InstallPath:String) [Get-ItemProperty], ItemNotFoundException
>    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand

**Comment by Mozoloa** [comment]
Are you sure you have 3.10.8 installed ? Try with HKLM instead of HKCU in the powershell command I gave you earlier

**Comment by Rizr09** [comment]
How do I fix it if HKLM works for me?

**Comment by Mozoloa** [comment]
Manually editing the code will just void my ability to help you on any further problem you may have with your installation since my time is limited.

Try the new 1.4.2 release instead, this might work if HKLM worked for you (I can see you original comment)

**Comment by Mozoloa** [comment]
the new 1.5 beta release should fix all of those issues, you don't even need to install python nor git
https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/releases/tag/V1.5-beta0
