### ISSUE TITLE
[Bug]: Failing to create Venv, python error

### ISSUE THREAD

**Issue by honda2** [EmpireMediaScience/A1111-Web-UI-Installer#24]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part, and this problem occured before I pressed "Launch WebUI"

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

I've installed 1.5.1 as first installer on fresh windows PC, 
Launcher won't launch WebUI, because it could not launch python.
In attempt to test previous release 1.4.2, non-portable python and git are installed, then installer ends with message bragging about newer version installed.
After this attempt, 1.5.1 succesfully starts webui, using non-portable python.

### Steps to reproduce the problem

1. install 1.5.1 on fresh windows
2. Run Launcher
3. Press Launch
4. Error occurs, Couldn't find python, something about venv
5. try to install 1.4.2, fail in halfway
6. try to run 1.5.1 again
7. it runs

### What should have happened?

It should properly set ENV variables to webui .bat

### Version of the Installer/Launcher where the problem happens

1.5.1

### Additional information, context and logs

If you've had some previous versions installed or python in PATH, then this error will exhibit itself in powershell window in path of used python executable used. 
It looks like default stable-diffusion webui needs to have some extra ENV variables set to work properly.

**Comment by Mozoloa** [comment]
I'm on it, it looks like it can't create the venv folder, it's very odd

**Comment by Mozoloa** [comment]
Found it, Python portable have no module installed, reverted to full install, but it's as automated as the portable install now

https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/releases/tag/V1.5.2

This release should fix everything, let me know
