### ISSUE TITLE
[Bug]: Git install fails on Windows 11

### ISSUE THREAD

**Issue by samuelboland** [EmpireMediaScience/A1111-Web-UI-Installer#25]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part, and this problem occured before I pressed "Launch WebUI"

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

During initial setup on Windows 11, git fails to clone the stable diffusion repository. This happens because the command to find the git executable on the system on line 14 is incorrect. It is currently: 

`git = os.environ.get('GIT', "git")`

This does not resolve to the git executable on Windows 11. I fixed it locally by changing it to:

`git = os.environ.get('GIT', "git") + '\git.exe'`

However, this would obviously not work on other operating systems. 

### Steps to reproduce the problem

1. Run the web_ui script
2. Wait for it to get to the part where it clones repositories
3. It fails.

### What should have happened?

It should clone the repositories.

### Version of the Installer/Launcher where the problem happens

1.55

**Comment by Mozoloa** [comment]
My install works en 11, where did you find this line ? Also you're not supposed to run the webui script, you need to launch from the shortwut at the root of the install folder
