### ISSUE TITLE
Feature Request: launch option on the launcher to bypass menu and instantly launch WebUI with last selected settings

### ISSUE THREAD

**Issue by BassJMagan** [EmpireMediaScience/A1111-Web-UI-Installer#28]
title...
Basically just some way to launch quicker, e.g. adding -launch to the end of the pin to task bar WebUI thing.

**Comment by Mozoloa** [comment]
Check this out https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/releases/tag/V1.5.6

**Comment by BassJMagan** [comment]
Sweet! Thanks for the addition.
