### ISSUE TITLE
[Bug]: fatal: repository 'https://github.com/AUTOMATIC1111/stable-diffusion-webui/' not found

### ISSUE THREAD

**Issue by Lissanro** [EmpireMediaScience/A1111-Web-UI-Installer#30]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part, and this problem occured before I pressed "Launch WebUI"

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

It tries to download non-existing repository https://github.com/AUTOMATIC1111/stable-diffusion-webui/. Also, in the UI itself, "Additional Launch Options (Click Here to See The List)" points to broken URL https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings. My guess "AUTOMATIC1111/stable-diffusion-webui" existed in the past, but was migrated somewhere else.

### Steps to reproduce the problem

1. Try to launch A1111 Web UI Installer, let it to try to download stable-diffusion-webui repo.

### What should have happened?

stable-diffusion-webui repository should have been successfully downloaded, if working URL was used.

### Version of the Installer/Launcher where the problem happens

V1.5.7

### Additional information, context and logs

```
 i   Settings file found, loading
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Updating Settings File
 ✓   SUCCESS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Launcher Version 1.5.7
 i   Launching without args
 i   Python 3.10 path found : C:\Users\Lissanro\AppData\Local\Programs\Python\Python310\python.exe
 i   Git found at C:\Program Files\Git
 i   Git is in PATH
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↓   Automatic1111 SD WebUI was not found, cloning git
Cloning into 'C:\Program Files\A1111 Web UI Autoinstaller\stable-diffusion-webui'...
warning: could not find UI helper 'GitHub.UI'
Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Device code
  3. Personal access token
option (enter for default):
info: please complete authentication in your browser...
remote: Repository not found.
fatal: repository 'https://github.com/AUTOMATIC1111/stable-diffusion-webui/' not found
 ✓   SUCCESS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Get-Content : Cannot find path 'C:\Program Files\A1111 Web UI
Autoinstaller\stable-diffusion-webui\.git\refs\heads\master' because it does not exist.
At C:\Program Files\A1111 Web UI Autoinstaller\Launcher\Functions.psm1:116 char:13
+     $hash = Get-Content $hashPath
+             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...fs\heads\master:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

```

**Comment by Mozoloa** [comment]
Your guess is as good as mine my dude, apparently the repos have disappeared
![image](https://user-images.githubusercontent.com/20817233/210758298-9e65590c-d2f5-47a1-94b0-a78e386f8a7c.png)

**Comment by Lissanro** [comment]
I manually cloned the repository from here: https://github.com/uservar/stable-diffusion-webui - it is marked as "This branch is up to date with AUTOMATIC1111/stable-diffusion-webui:master", which means it contains no changes to the original repo, and latest commit was pulled just 12 hours ago. So it should be as good as downloading the original repository.

**Comment by Lissanro** [comment]
I just found this - https://www.reddit.com/r/StableDiffusion/comments/103vsm2/webuis_new_home/, the repository wasn't removed by the author, but author's account was suspended by GitHub for unknown reason. According to the author, new home will be at GitGud https://gitgud.io/AUTOMATIC1111/stable-diffusion-webui/.

**Comment by Mozoloa** [comment]
I know but I don't have time to modify it right now, also this would probably break existing installs if they decide to update so I don't know what to do

**Comment by Mozoloa** [comment]
> go in `<Your install path>/A1111 Web UI Autoinstaller\stable-diffusion-webui` Open a terminal (right click in folder, open terminal) write : `git remote set-url origin https://gitgud.io/AUTOMATIC1111/stable-diffusion-webui`

updated readme with this fix=

**Comment by Mozoloa** [comment]
The github is back

**Comment by neyakira** [comment]
to rollback to the original git repo use this cmd : `git remote set-url origin https://github.com/AUTOMATIC1111/stable-diffusion-webui.git`
