### ISSUE TITLE
[Bug]:  i added --gradio-img2img-tool color-sketch and --gradio-inpaint-tool color-sketch to the additional launch options at a1111 and since then, a1111 doesnt start.  i removed them, still doesnt start. 

### ISSUE THREAD

**Issue by stjema** [EmpireMediaScience/A1111-Web-UI-Installer#31]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part, and this problem occured before I pressed "Launch WebUI"

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

 i added --gradio-img2img-tool color-sketch and --gradio-inpaint-tool color-sketch to the additional launch options at a1111 and since then, a1111 doesnt start.  i removed them, still doesnt start. 

### Steps to reproduce the problem

add --gradio-img2img-tool color-sketch --gradio-inpaint-tool color-sketch to "additional launch options" then click save. 
after clicking launch webui, the console closes and nothing starts.

### What should have happened?

webui starting

### Version of the Installer/Launcher where the problem happens

1.5.5

### Additional information, context and logs
webui-user.bat contains:
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=

call webui.bat

**Comment by paulescobar** [comment]
I have a similar problem. When I press 'Launch WebUI', it will do some updates...then suddenly exit. If I disable the update options, it will still exit abruptly.

Problem is...it happens so fast, I can't see what the actual error is. So I don't know what's causing this.

My last use of A1111, I applied the following settings (requirements for a specific model): 
_Go to Settings Tab > User Interface and paste this in the Quicksettings List field: sd_model_checkpoint, sd_vae, sd_hypernetwork, CLIP_stop_at_last_layers, sd_hypernetwork_strength_ 

I'm not saying that's what caused the problem, but it's the last thing I did - and sounds similar to OP's problem where a settings change seems to have messed up the launch.

**Comment by IanD-FM** [comment]
I think the issue was caused by an update to stablediffusion, after I updated it (using WebUI Launcher) I had this issue. Then just now I updated again and there was a new update, now there was a different issue, it was complaining about the --gradio-img2img-tool argument, so I removed that argument and now it at least launches again. Not sure if removing that argument has any other negative affects though.

**Comment by RealLightningslim** [comment]
My installation is also just flashing up and exiting instantly after I updated.

**Comment by RealLightningslim** [comment]
A re= reupdate fixed the "Flash and quit," but now when I try to run stable diffusion, it loads, I put in a small prompt, run it, and it kills the PC, and Windows (10) takes a while to sort itself out after a reboot.

**Comment by paulescobar** [comment]
Guys, I just ran it now and it works. Not sure if something changed in the update dynamics or what.

I'm beginning to wonder if my anti-virus was responsible. I typically put it on a standby mode when running such programs. This time I enabled it - and it actually prompted me to allow a bunch of stuff.

Anyways, it's running now and I don't see any errors.

**Comment by RandomHabit** [comment]
![error automatic1111](https://user-images.githubusercontent.com/47612698/211944166-7cd0cf5d-051e-4193-a5de-53c1d9dd5604.png)
I'm still having this issue. I've tried doing a fresh install. This was the last frame that I recorded before the Prompt closes

**Comment by Mozoloa** [comment]
can you try launching it from webui_user.bat in the stable diffusion webui folder ?

**Comment by RandomHabit** [comment]
Nothing happens when I right click and run. When I try to run it from the Command prompt I get an error from the working directory in the 'venv' folder "was unexpected at this time'

**Comment by Mozoloa** [comment]
I'd suggest a clean install, this seems to be a bug from the UI itself, if launching from webui user doesn't work then it's unrelated to the launcher

**Comment by RandomHabit** [comment]
So I changed to a different directory since I had done a "clean install" from the launcher once before and had also tried making it redownload Stable-Diffusion by deleting that from the folder as well prior. Changing directories for a real fresh install did it.
