### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rcourtman** [EmpireMediaScience/A1111-Web-UI-Installer#32]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part, and this problem occured before I pressed "Launch WebUI"

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

I've been using SD for a few days just fine but all of a sudden I get an error when launching. I can't tell if this is a problem with this repo or A11s, so apologise in advance if I've created an issue in the wrong repo:

`[INFO] WEBUI LAUNCHING VIA EMS LAUNCHER, EXIT THIS WINDOW TO STOP THE WEBUI
---------------
---------------
---------------
[WARNING] If you see the line 'commit hash : XXXX' or 'Installing Torch...' bellow, any error happening afterwards is not related to the launcher, but the WebUI itself which EMS is not affiliated with, we won't be able to help you fix those, you'll have to ask them on Automatic1111's github, not ours.
---------------
---------------
---------------
Cancel
venv "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: 0b8911d883118daa54f7735c5b753b5575d9f943
Installing requirements for Web UI
Launching Web UI with arguments: --autolaunch --medvram --xformers --ckpt-dir D:\Checkpoints
Traceback (most recent call last):
  File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 308, in <module>
    start()
  File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 299, in start
    import webui
  File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\call_queue.py", line 7, in <module>
    from modules import shared
  File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\shared.py", line 248, in <module>
    prompt_styles = modules.styles.StyleDatabase(styles_filename)
  File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\styles.py", line 50, in __init__
    for row in reader:
  File "C:\Users\court\AppData\Local\Programs\Python\Python310\lib\csv.py", line 111, in __next__
    row = next(self.reader)
_csv.Error: field larger than field limit (131072)
Press any key to continue . . .`

### Steps to reproduce the problem

Open launcher and hit Launch WEBUI

### What should have happened?

Launched SD on web address

### Version of the Installer/Launcher where the problem happens

1.4.0

### Additional information, context and logs

my launch options

--medvram --xformers --ckpt-dir 'D:\Checkpoints'

**Comment by Mozoloa** [comment]
That's after 'commit hash : XXXX' which means this is unrelated to the Launcher UI (it's written in gigantic lmao), it's probably an update that broke stuff on the side of the WebUI, also your version of the Launcher is outdated
