### ISSUE TITLE
[Bug]: doesnt work, i click install after picking folder but it does nothing once i click install

### ISSUE THREAD

**Issue by 2blackbar** [EmpireMediaScience/A1111-Web-UI-Installer#33]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part, and this problem occured before I see the "commit hash:" line in the console

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

clicked inswtall but theres nothing that could indicate progress, no files are being created and i still can edit path like if it was not installing at all which is probably what it is, like if install button was not clickable
Some indicator about installation being started would be nice.

### Steps to reproduce the problem

choose path, press install, nothing happens

### What should have happened?

should install

### Version of the Installer/Launcher where the problem happens

https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/commit/725bae231ca94cc31af3e7763e019356c400a336

**Comment by Mozoloa** [comment]
You didn't mention the launcher version you've used, commits =/= version. I've never seen that problem tho, have you tried leaving the default install and see if it works ?

**Comment by Poettidesign** [comment]
Bonjour Mozolla, André du Québec, Premièrement bravo pour ton initiative. J'ai un problème d'installation. Je te laisse un image pour te montrer ou s'arrête l'installation et mes compétences. Si tu peux m'aider, me guider, ça serait fortement apprécié. Merci
![troubleshootSD](https://user-images.githubusercontent.com/111206613/212771478-f12e021c-f2c7-4ff4-91cb-e107773fe71d.png)
