### ISSUE TITLE
Bonjour Mozolla, André du Québec, Premièrement bravo pour ton initiative. J'ai un problème d'installation. Je te laisse un image pour te montrer ou s'arrête l'installation et mes compétences. Si tu peux m'aider, me guider, ça serait fortement apprécié. Merci

### ISSUE THREAD

**Issue by Mozoloa** [EmpireMediaScience/A1111-Web-UI-Installer#34]
Bonjour Mozolla, André du Québec, Premièrement bravo pour ton initiative. J'ai un problème d'installation. Je te laisse un image pour te montrer ou s'arrête l'installation et mes compétences. Si tu peux m'aider, me guider, ça serait fortement apprécié. Merci
![troubleshootSD](https://user-images.githubusercontent.com/111206613/212771478-f12e021c-f2c7-4ff4-91cb-e107773fe71d.png)

_Originally posted by @Poettidesign in https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/issues/33#issuecomment-1384606647_

**Comment by Mozoloa** [comment]
@Poettidesign regardons ici plutôt, est ce la premiere fois que tu installe l'installer de manière clean ?

**Comment by Poettidesign** [comment]
Merci de ta réponse. Non, j'avais déjà essayé d'installer une version qui fonctionnait, mais l'interface était nulle. Puis, j'ai essayé d'installer la version 2.1 disons que c'était assez complexe et plutôt manuelle. J'ai du mettre à jour Python. J'ai aussi mis à la poubelle les anciennes versions pour ne pas nuire à l'installation de ta version. Mais, ça n'a pas fonctionné. Quand j'essaie d'installer avec ton Installer, il me dit qu'il y a déjà une version de SD d'installé. Merci de ton aide.

**Comment by Mozoloa** [comment]
Ou est ce que cela dit qu'il y a déjà une version de SD installé ?

**Comment by Mozoloa** [comment]
Il semblerait que ça soit les accents dans le path qui pose problème, moyen d'installer ça dans un sous dossier sans accent ni espace dans c:/ juste pour vérifier si c'est ça ?

**Comment by Poettidesign** [comment]
je vais essayé. Vraiment merci de ton aide.
