### ISSUE TITLE
[Bug]: fatal: update_ref failed for ref 'ORIG_HEAD': cannot lock ref 'ORIG_HEAD':

### ISSUE THREAD

**Issue by The-Great-Nothing** [EmpireMediaScience/A1111-Web-UI-Installer#38]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part, and this problem occured before I see the "commit hash:" line in the console

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

Windows 10. When starting the app with the given shortcut this message appears:

Updating Webui
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 20 (delta 10), reused 10 (delta 5), pack-reused 0
Unpacking objects: 100% (20/20), 18.69 KiB | 303.00 KiB/s, done.
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
   1bfec87..d5ce044  master     -> origin/master
fatal: update_ref failed for ref 'ORIG_HEAD': cannot lock ref 'ORIG_HEAD': unable to resolve reference 'ORIG_HEAD': reference broken

After that all "seems" to work normally.

### Steps to reproduce the problem

Just start the program with the provided shortcut.

### What should have happened?

Probably not a "fatal: update_ref failed " message.

### Version of the Installer/Launcher where the problem happens

A1111.Web.UI.Autoinstaller.v1.5.8

**Comment by Mozoloa** [comment]
try to remove the ORIG_HEAD file in stable-diffusion-webui/.git and redo an update

**Comment by The-Great-Nothing** [comment]
I have to buy you coffee. Fixed.
