### ISSUE TITLE
Allow clearing non-default image directories

### ISSUE THREAD

**Issue by noahkiss** [EmpireMediaScience/A1111-Web-UI-Installer#39]
**Describe the solution you'd like**
I recently realized that the "clear generated images" checkbox was not working for me, because I have a different directory defined in A1111's settings. It would be great if either the launcher could read that from my A1111 settings or if I could specify the root directory which contains the output folders. (A bonus feature would be a way to skip the "confirm" dialogue!)

**Comment by Mozoloa** [comment]
Checkout the latest release my good man

**Comment by noahkiss** [comment]
@Mozoloa Thank you, and apologies for the late reply!

**Comment by noahkiss** [comment]
Hey Mozoloa, I realized this still isn't working for me because I'm setting specific directories instead of the main custom directory option. Would it be possible to modify the launcher to clear all of the following directories? 

outdir_samples
outdir_txt2img_samples
outdir_img2img_samples
outdir_extras_samples
outdir_grids
outdir_txt2img_grids
outdir_img2img_grids

[Here's where the original change was made](https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/blob/3e4dbb14c06482ea20f372aadf38a133061e2aea/Launcher/Functions.psm1#L347) and here's the commit: 39c70e6218d43e216abf8d2a3f1cdc3f636bd431

Thank you again!

**Comment by Mozoloa** [comment]
The outdir samples is the only one covered right now as said in the Readme, it should normally encompass all the sub folders in it.

Have you replaced all the paths there to totally different paths ?

Can you show me your `A1111 Web UI Autoinstaller\stable-diffusion-webui\config.json` file please

**Comment by noahkiss** [comment]
I set the folders specifically to keep everything more organized, so my `outdir_samples` is empty, causing nothing to get cleaned up. Here's the relevant snippet from my config.json file:

```json
[
    "temp_dir": "",
    "clean_temp_dir_at_start": true,
    "outdir_samples": "",
    "outdir_txt2img_samples": "D:\\outputs\\txt2img-images",
    "outdir_img2img_samples": "D:\\outputs\\img2img-images",
    "outdir_extras_samples": "D:\\outputs\\extras-images",
    "outdir_grids": "",
    "outdir_txt2img_grids": "D:\\outputs\\txt2img-grids",
    "outdir_img2img_grids": "D:\\outputs\\img2img-grids",
    "outdir_save": "D:\\saved",
    "save_to_dirs": false,
    "grid_save_to_dirs": false,
    "use_save_to_dirs_for_ui": false,
]
```

Here's how it looks in my WebUI

![image](https://user-images.githubusercontent.com/22437387/221912753-fe08c550-8a5c-454e-a89c-96a50cdc237a.png)

**Comment by Mozoloa** [comment]
Thanks ! I'll have a look

**Comment by Mozoloa** [comment]
Something is telling me I shouldn't include the "saved" folder in the clearing ? Am I wrong ?

**Comment by noahkiss** [comment]
Correct, just the others

**Comment by Mozoloa** [comment]
I'll have a look whenever I have time !

**Comment by Mozoloa** [comment]
Adding this to the V2 project so it doesn't go stale
