### ISSUE TITLE
[Bug]: Issues with Powershell 7.4.0

### ISSUE THREAD

**Issue by AdrianoCahete** [EmpireMediaScience/A1111-Web-UI-Installer#40]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part, and this problem occured before I see the "commit hash:" line in the console

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

On launch, when searching for Python, the follow powershell error is shown:

First run (install process):
```
 i   Python is in PATH
The property 'Path' cannot be found on this object. Verify that the property exists.
At D:\stable-diffusion\A1111-UI\Launcher\Functions.psm1:47 char:9
+         $Global:gitPath = $gitInPath.Path
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

The property 'Path' cannot be found on this object. Verify that the property exists.
At D:\stable-diffusion\A1111-UI\Launcher\Functions.psm1:48 char:57
+ ...     logger.info "Git found and already in PATH at $($gitInPath.Path)"
+                                                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
```

Posteriors runs:
```
 i   Launcher Version 1.5.10
 i   No Launcher launch options
 i   Python 3.10 found : C:\Users\xxxxxx\AppData\Local\Programs\Python\Python310\python.exe
 i   Python is in PATH
The property 'Path' cannot be found on this object. Verify that the property exists.
At D:\stable-diffusion\A1111-UI\Launcher\Functions.psm1:47 char:9
+         $Global:gitPath = $gitInPath.Path
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

The property 'Path' cannot be found on this object. Verify that the property exists.
At D:\stable-diffusion\A1111-UI\Launcher\Functions.psm1:48 char:57
+ ...     logger.info "Git found and already in PATH at $($gitInPath.Path)"
+                                                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
```

Idea: Put a warning to close the terminal when install is done, so the env variables can load properly.
Aside that, everything works as expected.

### Steps to reproduce the problem

1. Install Powershell 7.4.0
2. Run installer for first time

### What should have happened?

No errors to display

### Version of the Installer/Launcher where the problem happens

1.5.10

**Comment by Mozoloa** [comment]
That's pretty odd, are you sure this is related to powershell 7.4 ?

**Comment by AdrianoCahete** [comment]
Seems to be. I have git installed to other projects and is working well.

I know that PS7 changed a little bit, but don't know exactly what.

**Comment by Mozoloa** [comment]
Have you tried to temporarily uninstall PS7 to see if it launches properly ?

**Comment by AdrianoCahete** [comment]
It's launching ok, is working fine, but the installer gives me this error. I think that it may cause problems if the user who is installing doesn't have git installed.

**Comment by Mozoloa** [comment]
If the user doesn't have git, it installs it automatically and place it in path

**Comment by Mozoloa** [comment]
I think I've found the issue, the object that I get when fetching info did not have a "path" property yet it did correctly return the "source" key and I was confused but it worked so didn't "fix" it, this may have been some legacy stuff that got canned in 7. I changed it to the "source" key instead and it still works on earlier version, maybe that was it ? 

release with the fix :
https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/releases/tag/V1.5.11

**Comment by AdrianoCahete** [comment]
Fixed! :)

```
 i   Settings file found, loading
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Updating Settings File
 ✓   SUCCESS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Launcher Version 1.5.11
 i   Found a custom WebUI Config
 i   No Launcher launch options
 i   Python 3.10 found : C:\Users\xxxxx\AppData\Local\Programs\Python\Python310\python.exe
 i   Python is in PATH
 i   Git found and already in PATH at
 i   Automatic1111 SD WebUI found at D:\stable-diffusion\A1111-UI\stable-diffusion-webui
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Opening A1111 WebUI Launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Arguments are now: --xformers --administrator

```

**Comment by Mozoloa** [comment]
Your log seems to not show the path of git at all, could you try this code directly in powershell and tell me what it returns ?

```ps
$gitInPath = Get-Command git -ErrorAction SilentlyContinue
$gitInPath.Source
```

**Comment by AdrianoCahete** [comment]
> Your log seems to not show the path of git at all, could you try this code directly in powershell and tell me what it returns ?

Good catch.

> $gitInPath = Get-Command git -ErrorAction SilentlyContinue
> $gitInPath.Source

Is empty because I have an alias from **git** to [**hub**](https://hub.github.com/).
```
λ Get-Command git

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           git -> hub.exe
```

```
λ Get-Command hub

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     hub.exe                                            1.0.0.0    C:\ProgramData\chocolatey\bin\hub.exe
```

**Comment by Mozoloa** [comment]
this is highly unlikely than anyone else using this launcher will have such a customized setup so I think I won't bother fixing this since it's working lmao

**Comment by AdrianoCahete** [comment]
Yep, np! It's working on PS 7, it's OK!
