### ISSUE TITLE
Progress status for downloads

### ISSUE THREAD

**Issue by Artemonim** [EmpireMediaScience/A1111-Web-UI-Installer#43]
**Is your feature request related to a problem? Please describe.**
When downloading a neural network model in PowerShell, there is a message about the start of the download, but it is impossible to know the progress.

**Describe the solution you'd like**
Count every _n_ seconds how many percent have already been loaded.

**Describe alternatives you've considered**
...also count the estimated time.

**Comment by Mozoloa** [comment]
I've tried to make a progress bar with PowerShell but turns out they're literally slowing the downloads lmao (not kidding), I'll try to create some sort of parallel process maybe, that checks the file size maybe that could work ! Not sure when I'll have the time

**Comment by Mozoloa** [comment]
I've worked on something on the latest release, tell me if it's good

**Comment by Mozoloa** [comment]
This was done in the latest release, if any glitch arise with the new % and time remaining, please open an issue
