### ISSUE TITLE
Add a "open containing folder" button, to open the folder containing this launcher

### ISSUE THREAD

**Issue by Walmann** [EmpireMediaScience/A1111-Web-UI-Installer#45]
I would like a button to open the folder containing this launcher, as it would speed up the process of adding new models, view outputs etc. from the WebUI.

**Comment by Mozoloa** [comment]
I believe those options are already in the webui, and I would advise not adding models in the webui folder, rather use an external folder so the models aren't nuked if you clean install or reset using the red button in the launcher

**Comment by Mozoloa** [comment]
Done in the latest release with the "browse" button
https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/releases/latest
