### ISSUE TITLE
Allow choosing whether `autolaunch` option is called

### ISSUE THREAD

**Issue by oakif** [EmpireMediaScience/A1111-Web-UI-Installer#46]
**Is your feature request related to a problem? Please describe.**
I tried adding `--autolaunch=False` as an option to my command line arguments, but this causes it to fail, presumably because the launcher always puts the `--autolaunch` option in the command line arguments. 

The reason I want this is because I use SD in a non-default browser, so I always have to keep closing the tab that opens up in my default browser. 

**Describe the solution you'd like**
It would be nice to be able to select whether or not to autolaunch the UI.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Mozoloa** [comment]
I'm not sure there'll be enough demand for this to become an actual feature, but you can remove `"--autolaunch" +`  from this line (89) in launchUI.ps1 in you launcher folder: 

[    $env:COMMANDLINE_ARGS = "--autolaunch " + $arguments](https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/blob/dada3ba0d9e2b6534fcd6dfc623f8aaea59335fe/Launcher/LauncherUI.ps1#L89)

**Comment by Mozoloa** [comment]
I created a launch option to do exactly that while updating some stuff, checkout the latest release
https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/releases/latest

Check at the bottom of the readme to see how to do it

**Comment by oakif** [comment]
This works great! Thanks a lot for the option and the suggestion.
