### ISSUE TITLE
Open in Windows Terminal instead of standard PowerShell/Command Prompt

### ISSUE THREAD

**Issue by oakif** [EmpireMediaScience/A1111-Web-UI-Installer#47]
**Is your feature request related to a problem? Please describe.**
I like Windows Terminal a lot more than the standard command prompt (more features, easier customization options, support for tabs, better UI/layout, etc. in Windows Terminal). 

**Describe the solution you'd like**
It would be nice to have the command prompt open in a Windows Terminal window instead, if possible. 

**Describe alternatives you've considered**
I've thought a little bit about how to do this. I think it might be possible to change the "target" from `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe` to use an instantiation of Windows Terminal's PowerShell instead. Unfortunately I don't know too much about how Windows works to be able to figure out how this should be done. Maybe someone reading this will have some tips? 

**Additional context**
N/A

**Comment by Mozoloa** [comment]
I don't understand what you mean, the powershell window is just showing log you're not supposed to interact with it at all

**Comment by oakif** [comment]
Then I guess is it possible to view the log in windows terminal?

**Comment by Mozoloa** [comment]
No idea, you could try replacing the powershell path with a terminal path and see if it works, I chose the default powershell as it's what i'm using to code

**Comment by Mozoloa** [comment]
I think this is very niche so I might not implement it especially since I'm not sure everyone has in on W10, but you can modify the shortcut yourself by changing the target to the following

`wt.exe -d "[InstallPath]\Launcher" -p "Windows.PowerShell" powershell.exe -File "[InstallPath]\Launcher\LauncherUI.ps1"`

replace [InstallPath] with the overall A1111 WebUI Autoinstaller path

**Comment by oakif** [comment]
Thanks a lot for the suggestion! Can you tell me a bit more about which shortcut you're talking about? The only shortcut I have is the `A1111 WebUI (Pin to Taskbar)` shortcut, which has the following Target: 

`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File "C:\Users\username\A1111 Web UI Autoinstaller\Launcher\LauncherUI.ps1"`

It turns out that if I try to run `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe` from Windows Start, it opens in Windows Terminal. What is the `wt.exe` executable in your comment?

**Comment by Mozoloa** [comment]
Windows terminal is based on powershell I believe, it's possible that now they're both mixed together on later versions of windows so that should be what opens when you launch the launcher in the end

**Comment by oakif** [comment]
Here is an example of what I mean to make it a little clearer. The current is what opens:

![image](https://user-images.githubusercontent.com/48932412/218312799-89dd6117-9cfe-4e7b-a680-fd858fcde803.png)

And this is PowerShell in Windows Terminal:

![image](https://user-images.githubusercontent.com/48932412/218312832-cc0f1f13-5913-4596-bcbf-952942c453bc.png)

Windows Terminal has tab features (e.g. if I want to open multiple instances of the WebUI, I can have the windows tabbed together), and it also offers much better support for copying text (easier to select, no need to press Control+C, etc.), and also the scrolling isn't as bad (it's impossible to scroll up on a normal PowerShell prompt). 

I'll try to mess around with the Target in the shortcut a bit more and see if I can force it to open in Windows Terminal.

**Comment by Mozoloa** [comment]
What's very odd is I actually get the second one by default on W11

**Comment by oakif** [comment]
Oh my, that's strange! I'll make a post on SuperUser to ask about it. I'm on the latest version of Windows 11 so it should be working for me too if it's working for you!

**Comment by Mozoloa** [comment]
Okay nevermind it's actually launching a simpler window, but using my wt.exe change of the shortcut it works well, altho I remember the terminal closing when launching the actual webui, so no idea how to close it afterwards. I haven't tested again so maybe that was just a fluke

**Comment by oakif** [comment]
Hmm yes it looks like you're right, when I run your command in Windows Terminal, it seems to work fine initially, but upon clicking "Launch WebUI" the PowerShell tab exits and disappears
