### ISSUE TITLE
[Bug]: Low resolution in app

### ISSUE THREAD

**Issue by oakif** [EmpireMediaScience/A1111-Web-UI-Installer#49]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part, and this problem occured before I see the "commit hash:" line in the console

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

Hi, it looks like on a high-DPI display, the application itself shows a pretty low resolution. Here is an example of what the installer looks like (high resolution):

![image](https://user-images.githubusercontent.com/48932412/218312658-22161fef-29db-41e8-b545-c373b1877f43.png)

And here's an example of the actual application: 

![image](https://user-images.githubusercontent.com/48932412/218312684-97b60979-149f-4131-8a93-2b15c20a115c.png)

### Steps to reproduce the problem

N/A

### What should have happened?

The application should also support high-DPI scaling

### Version of the Installer/Launcher where the problem happens

1.7.0

**Comment by Mozoloa** [comment]
I'm not sure where's the problem here, the app has fixed pixel size so it should look small on high dpi displays, but I have no idea how small, your pics are just pics of the interface Idk what to look at

**Comment by oakif** [comment]
This pic might make it a bit clearer: 

![image](https://user-images.githubusercontent.com/48932412/218393193-8a66a20a-3382-4dde-a0cb-18625380f831.png)

Coming from macOS where UI scaling is always consistent system-wide, I have a pretty sharp eye for these things (no pun intended). Many native Windows 11 apps don't scale properly either

**Comment by Mozoloa** [comment]
Yeah that's a winforms problems I believe with windows, it just scales the whole thing up, I'll try to fix it in V2

**Comment by imppresser** [comment]
![image](https://user-images.githubusercontent.com/10281931/219461517-c296d047-90d8-43ba-b270-3f37dc93b702.png)
1.7.0 version is like the image, inappropriately.
env: 4k win11 150% scaled.
former 1.5.7 version is appropriate.

**Comment by Mozoloa** [comment]
![image](https://user-images.githubusercontent.com/20817233/219464948-c6d336ee-9573-4cfd-8870-3155cae5b507.png)
Don't mind the version number, that's 1.7.0 on 4K win 11 125%, makes no sense lmao

**Comment by imppresser** [comment]
So I have no idea, will update V2 fix?

**Comment by Mozoloa** [comment]
I don't yet know how to fix this but I'll try. V2 is going to use a custom made UI library and I'll try to bake some scaling settings in it

**Comment by imppresser** [comment]
It sounds like this will go well, looking forward to the release of V2
