### ISSUE TITLE
[Bug]: RuntimeError: Cannot add middleware after an application has started

### ISSUE THREAD

**Issue by LainX84** [EmpireMediaScience/A1111-Web-UI-Installer#50]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part, and this problem occured before I see the "commit hash:" line in the console

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

`Model loaded in 2.7s (load weights from disk: 0.3s, create model: 0.4s, apply weights to model: 0.4s, apply half(): 0.5s, move model to device: 0.4s, load textual inversion embeddings: 0.6s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\magri\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 361, in <module>
    start()
  File "C:\Users\magri\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 356, in start
    webui.webui()
  File "C:\Users\magri\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\webui.py", line 232, in webui
    app.add_middleware(GZipMiddleware, minimum_size=1000)
  File "C:\Users\magri\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 135, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")
RuntimeError: Cannot add middleware after an application has started`

### Steps to reproduce the problem

Star the application.
Waiting some jobs do iteself.
Error.

### What should have happened?

After the install at the 1st time i run the application, appear the errror "RuntimeError: Cannot add middleware after an application has started" and after i press enter the application close itself.

### Version of the Installer/Launcher where the problem happens

1.7.0

**Comment by Mozoloa** [comment]
You checked and acknowledged that this bug happened before the "commit hash" line, yet the log you're providing is way after, so it's very likely unrelated to my Launcher as stated in the warning you're supposed to have read and acknowledged as well.
