### ISSUE TITLE
[Bug]: Unable to start web UI after install

### ISSUE THREAD

**Issue by teslashark** [EmpireMediaScience/A1111-Web-UI-Installer#51]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part, and this problem occured before I see the "commit hash:" line in the console

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

Installing gfpgan
Traceback (most recent call last):
  File "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 360, in <module>
    prepare_environment()
  File "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 275, in prepare_environment
    run_pip(f"install {gfpgan_package}", "gfpgan")
  File "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 137, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install gfpgan.
Command: "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379
  Cloning https://github.com/TencentARC/GFPGAN.git (to revision 8d2447a2d918f8eba5a4a01463fd48e45126a379) to c:\users\ggsha\appdata\local\temp\pip-req-build-7f13vxki

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\ggsha\AppData\Local\Temp\pip-req-build-7f13vxki'
  fatal: unable to access 'https://github.com/TencentARC/GFPGAN.git/': Recv failure: Connection was reset
  fatal: could not fetch fa702eeacff13fe8475b0e102a8b8c37602f3963 from promisor remote
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

  error: subprocess-exited-with-error

  git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\ggsha\AppData\Local\Temp\pip-req-build-7f13vxki' did not run successfully.
  exit code: 128

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\ggsha\AppData\Local\Temp\pip-req-build-7f13vxki' did not run successfully.
exit code: 128

See above for output.

### Steps to reproduce the problem

1. Go to install folder
2. Press A1111 WebUI (Pin to Taskbar)
3. Wait

### What should have happened?

The WebUI should have been activated.

### Version of the Installer/Launcher where the problem happens

1.7.0

### Additional information, context and logs

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading A111 WebUI Launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Settings file found, loading
 →   Updating Settings File  ✓
 i   Launcher Version 1.7.0
 i   No Launcher launch options
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Checking requirements :
 i   Python 3.10.6150.1013 found in registry:  C:\Users\ggsha\AppData\Local\Programs\Python\Python310\
 i   Clearing PATH of any mention of Python
 →   Adding python 3.10 to path  ✓
 i   Git found and already in PATH:  C:\Program Files\Git\cmd\git.exe
 i   Automatic1111 SD WebUI found:  E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui
 i   One or more checkpoint models were found
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading Complete, opening launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Arguments are now: --xformers --ckpt-dir 'E:\AIpaint\checkpoint'
 i   Arguments are now: --xformers --ckpt-dir 'E:\AIpaint\checkpoint'
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  WEBUI LAUNCHING VIA EMS LAUNCHER, EXIT THIS WINDOW TO STOP THE WEBUI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 !   Any error happening after 'commit hash : XXXX' is not related to the launcher. Please report them on Automatic1111's github instead :
 ☁   https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/new/choose
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cancel
venv "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39
Installing gfpgan
Traceback (most recent call last):
  File "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 360, in <module>
    prepare_environment()
  File "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 275, in prepare_environment
    run_pip(f"install {gfpgan_package}", "gfpgan")
  File "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 137, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install gfpgan.
Command: "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379
  Cloning https://github.com/TencentARC/GFPGAN.git (to revision 8d2447a2d918f8eba5a4a01463fd48e45126a379) to c:\users\ggsha\appdata\local\temp\pip-req-build-7f13vxki

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\ggsha\AppData\Local\Temp\pip-req-build-7f13vxki'
  fatal: unable to access 'https://github.com/TencentARC/GFPGAN.git/': Recv failure: Connection was reset
  fatal: could not fetch fa702eeacff13fe8475b0e102a8b8c37602f3963 from promisor remote
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

  error: subprocess-exited-with-error

  git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\ggsha\AppData\Local\Temp\pip-req-build-7f13vxki' did not run successfully.
  exit code: 128

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\ggsha\AppData\Local\Temp\pip-req-build-7f13vxki' did not run successfully.
exit code: 128

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip available: 22.2.1 -> 23.0.1
[notice] To update, run: E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip

**Comment by teslashark** [comment]
Update after attempting to set proxy: Still unable to start
```

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading A111 WebUI Launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Settings file found, loading
 →   Updating Settings File  ✓
 i   Launcher Version 1.7.0
 i   No Launcher launch options
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Checking requirements :
 i   Python 3.10.6150.1013 found in registry:  C:\Users\ggsha\AppData\Local\Programs\Python\Python310\
 i   Clearing PATH of any mention of Python
 →   Adding python 3.10 to path  ✓
 i   Git found and already in PATH:  C:\Program Files\Git\cmd\git.exe
 i   Automatic1111 SD WebUI found:  E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui
 i   One or more checkpoint models were found
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading Complete, opening launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Arguments are now: --xformers --ckpt-dir 'E:\AIpaint\checkpoint'
 i   Arguments are now: --xformers --ckpt-dir 'E:\AIpaint\checkpoint'
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  WEBUI LAUNCHING VIA EMS LAUNCHER, EXIT THIS WINDOW TO STOP THE WEBUI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 !   Any error happening after 'commit hash : XXXX' is not related to the launcher. Please report them on Automatic1111's github instead :
 ☁   https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/new/choose
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cancel
venv "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39
Installing gfpgan
Installing clip
Installing open_clip
Installing xformers
Cloning Stable Diffusion into repositories\stable-diffusion-stability-ai...
Cloning Taming Transformers into repositories\taming-transformers...
Cloning K-diffusion into repositories\k-diffusion...
Cloning CodeFormer into repositories\CodeFormer...
Cloning BLIP into repositories\BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI
Launching Web UI with arguments: --autolaunch --xformers --ckpt-dir E:\AIpaint\checkpoint
Calculating sha256 for E:\AIpaint\checkpoint\v1-5-pruned.ckpt: e1441589a6f3c5a53f5f54d0975a18a7feb7cdf0b0dee276dfc3331ae376a053
Loading weights [e1441589a6] from E:\AIpaint\checkpoint\v1-5-pruned.ckpt
Creating model from config: E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading (…)olve/main/vocab.json: 100%|███████████████████████████████████████████| 961k/961k [00:01<00:00, 767kB/s]
Downloading (…)olve/main/merges.txt: 100%|███████████████████████████████████████████| 525k/525k [00:00<00:00, 559kB/s]
Downloading (…)cial_tokens_map.json: 100%|█████████████████████████████████████████████| 389/389 [00:00<00:00, 425kB/s]
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████| 905/905 [00:00<00:00, 567kB/s]
Downloading (…)lve/main/config.json: 100%|████████████████████████████████████████| 4.52k/4.52k [00:00<00:00, 3.19MB/s]
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 28.9s (calculate hash: 6.1s, load weights from disk: 2.6s, create model: 16.2s, apply weights to model: 0.8s, apply half(): 0.8s, move model to device: 0.8s, load textual inversion embeddings: 1.7s).
Traceback (most recent call last):
  File "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 361, in <module>
    start()
  File "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 356, in start
    webui.webui()
  File "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\webui.py", line 210, in webui
    app, local_url, share_url = shared.demo.launch(
  File "E:\AIpaint\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1418, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True.
```

**Comment by Mozoloa** [comment]
From your own log:

 **!   Any error happening after 'commit hash : XXXX' is not related to the launcher. Please report them on Automatic1111's github instead :
 ☁   https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/new/choose**

and just a few line bellow before your errors: 
**Commit hash:** 3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39

Please read the warnings and actually read the readme instead of just checking the box pretending you did
