### ISSUE TITLE
[Bug]: Installer has unsane path-default to Documents, which is especially a problem when OneDrive is enabled

### ISSUE THREAD

**Issue by claudiusraphael** [EmpireMediaScience/A1111-Web-UI-Installer#52]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part

### Did this problem occur before the "commit hash:" line in the log ?

- [X] I swear that this problem occurred before the "commit hash:" line in the log, and that if it has instead occured after, I owe the devs a $10.000 donation.

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

The installer defaults to the users Documents-folder. This is since 2012 (Windows 8), not a sane approach as it can not be guaranteed that Documents is actually in C:\Users\Username\Documents, but instead "hijacked" by OneDrive. The latter is the DEFAULT-state for any Windows-installation since Windows 10 19H2 and on Windows 10/11 22H2 it can only be circumvented by force-killing the Installer-UI after disrupting network-connection, as for standard-versions the Installer doesn't even offer to install into Domain (aka Non-Microsoft-Account, but local) - this is only an option if you acquire an .iso and prepare an installer with a 3rd-party tool like Rufus, or use .iso-boot for example via ventoy.

Using Documents was at no point in existence of Windows a sane place to store any kind of Apps, no matter how small, especially not Applications that are automatically installed and have dependencies on multiple apps/scripts/libraries/etc. - Documents is exclusively designed by default to be shared/synced easily by 3rd-party tools, boot-scripts and since Windows 8 WILL be automatically hijacked by Windows and redirected to OneDrive, which is NOT reversible completely, if at all (which depends on a gazillion things).

Please do not ever use Documents for anything but the smallest possible files, namely: Txxt-files (which are hard-limited by default to 64kB in Windows and interchangeable files like the diverse Office-formats and scripts/code-snippets.

And to those that want to chime in to state "just use another folder": No, recommending to create a folder in the ROOT of a system-drive is likewise in Linux and Windows an unsane idea.

There are for both systems default folders for these tasks, depending on the necessities. Ignoring these defaiults only leads to either corrupted installs due to security-checks or to users tampering with the systems rights-system and most probably open it up to intrusion.

short version: Just don't. It ain't workable anymore. Windows Client versions (Home, Pro, Single Language) from 10 19H2 up are strictly SaaS (Software-as-a-Service) and enforce (in many cases without user-interaction) to follow its rulesets.

### Steps to reproduce the problem

1. Have a "DEFAULT"-install of any Windows 10 Client (Home/Pro/SingleLanguage) 19H2 or higher, which IMPLIES MS-Account and OneDrive
2. Execute the Installer for A1111 Web UI
3. Have luck and get (due to the right CUSTOM settings) shown that you are not installing LOCALLY but into OneDrive ...

![image](https://user-images.githubusercontent.com/84972255/221398766-0e2e5784-f367-4c48-a3ca-9f7abf2e1d1d.png)

### What should have happened?

It should offer to install into one of the possible default-directories for locally installed applications, depending if User-Specific or System-Wide.

If an installer utilizes the registry, announces itself to the system to offer automated un-installation and shall be system-wide available it goes into either "Program Files", "Program Files (x86)" or "ProgramData" - depending on its type. If it is user-specific then it is stored in the diverse subsections of the Users' AppData-subfolders, depending on its type.

If these defaults can not be used because the installer does not comply to the given rules, then it should be deployed either in its own Folder-Structure directly under the users-root (alongside Documents, etc.) and be registered in the Favorites and/or Libraries of the Explorer or as a Docker-image or alternatively in the "Public"-UserAccount-Directory-Structure, that is if it is and should be publically accessible. The latter is the safe alternative to storing an application in the root of the system-drive. Besides that it can only be deployed onto another partition/drive/StorageSpace/iSCSI-target and the likes.

Hope this gives an idea.

### Version of the Installer/Launcher where the problem happens

1.7.0

### Additional information, context and logs

All necessary said.

**Comment by claudiusraphael** [comment]
Additon: If the installer does not register with the system at all, basically just collecting files and store them in relation to each other, then it might be wise to default ot the Downloads-folder and create a folder inside that, where all files are gathered and collected. Because then it is user-specific, does not need any rights-modification, can still be checked by Defender and the likes and allows the user to easily move it anywhere the user wishes to. The Downloads-folder is also one of the few folders inside the users directory that is guaranteed to not be touched by OneDrive and similar tools, but can and is still be redirectable by the user and/or adminsitrator to another partition, a virtual-drive, an external drive, a storagespace, a network-folder, etc.

**Comment by Mozoloa** [comment]
I'm sorry but I really don't understand like 90% of what you said here. I think there's way too much unnecessary and unrelated information.

The Launcher is in documents by default as it's easier to find for me and most users, it also makes it easier for people that store all their models & outputs in the default folders. On top of that it can be moved around as all script paths are relative, it doesn't matter where it is, the worst that can happen is you have to change the target of the shortcut.

So in effect yes you can just choose another folder during the install, the suggested Documents path is completely arbitrary for simplicity and can be changed, that's the whole point of the dialog. I can't be responsible if you didn't want to install in this specific default path but didn't change it.

If your default document path has been hijacked by onedrive, that's something [you can fix on your machine even if the default way doesn't work](https://support.microsoft.com/en-us/topic/operation-to-change-a-personal-folder-location-fails-in-windows-ffb95139-6dbb-821d-27ec-62c9aaccd720), so yes it can be guaranteed that's it's in the right path (Or you could just check that there's no /onedrive/ in the path suggested, not that hard). I can't create if statements for every broken windows install that's not sustainable.

Also the only registry entry it creates is `hkcu:\Software\Empire Media Science\A1111 Web UI Autoinstaller` and just has path & version, you should be able to uninstall by running the installer again and clicking remove.

**Comment by claudiusraphael** [comment]
The "problem" is, that by default you do not get shown/be informed that OneDrive "hijacked" your Documents-path and therefore anything stored in Documents will be stored in your Online-Quota.

This does impact the overall performance, lead to issues like not being able execute modules (because these are stored online not locally) and preventing an installer from tracing any bugs as it "thinks" it is executed locally, while in fact it is executed in the OneDrive network-storage.

**Comment by claudiusraphael** [comment]
And regarding the linked "fix on your machine if the default way doesn't work" - this is not applicable to regular Windows Client-versions since Windows 10 19H2 (which is what i already explained). The "hijacking" is by default and not treated as a bug - but a feature - by Microsoft.
 
The only way to not be hijacked is to create a local-account and prevent OneDrive from being executed at all via Group-Policy and by actively blocking it in Defender and Firewall.

Since developers/distributors are encouraged to deploy applications solely via Microsoft Store and this is already happening on a broad scale there is no way around linking your local user-account with your Microsoft-Account.

I was trying to point out a massive and severe flaw in the installer that can wreak havoc on an interested users PC, without even informing the user about the implications, as they are exactly that: "implied", by Microsoft.

Use this information, or don't - i don't care -  i left this issue/note for anybody who wonders why the installer takes ages to even begin working, does magically not use any space locally and why Windows suddenly pops "seemingly totally unrelated" messages about the OneDrive-Quota being exceeded, that is if these notifications are not disabled.

Have a nice one.
