### ISSUE TITLE
[Bug]: EXE and MSI file signature mismatch 

### ISSUE THREAD

**Issue by GregariousJB** [EmpireMediaScience/A1111-Web-UI-Installer#55]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part

### Did this problem occur before the "commit hash:" line in the log ?

- [X] I swear that this problem occurred before the "commit hash:" line in the log, and that if it has instead occured after, I owe the devs a $10.000 donation.

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

EXE and MSI file signature mismatch error

### Steps to reproduce the problem

1. Run installer
2. Set directory to `D:/A1111WebUI`
3. "Clean install" is kept checked
4. Install
5. Immediate error

### What should have happened?

No error.

### Version of the Installer/Launcher where the problem happens

1.7.0

### Additional information, context and logs

![bug](https://i.imgur.com/pMhWAtc.png)

Also tried running as Administrator. Same problem.

**Comment by Mozoloa** [comment]
Interesting, do you get the same error if you place it in the default folder ?

**Comment by Mozoloa** [comment]
not stale, bad bot, I haven't time to look into it yet

**Comment by Mozoloa** [comment]
No installer for V2, so this should be fixed lmao
