### ISSUE TITLE
[Bug]: Launcher couldn't start Python

### ISSUE THREAD

**Issue by LordOfTheSnow** [EmpireMediaScience/A1111-Web-UI-Installer#59]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part

### Did this problem occur before the "commit hash:" line in the log ?

- [X] I swear that this problem occurred before the "commit hash:" line in the log, and that if it has instead occured after, I owe the devs a $10.000 donation.

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

I was running a manual installation of StableDiffusion (with Python 3.10) and was trying to integrate ControlNet which didn't work.

That's why I want to try a new clean installation and used the A1111-Web-UI-Installer.

It all went relatively smooth until I clicked "Launch WebUI". The launcher then displays an error message that it couldn't launch python (see below).

I am aware that I am running not the recommended Python version 3.6 but the error message indicates a general problem, I assume. My own manual SD installation works fine under Python 3.10 until it tries to install the ControlNet UI extension.

Removing Python 3.10 altogether is not an option since I need it for other projects.

### Steps to reproduce the problem

1. In the Launcher click "LAUNCH WEBUI"

### What should have happened?

The SD web ui should have been accessable under localhost:7860

### Version of the Installer/Launcher where the problem happens

1.7.0

### Additional information, context and logs

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading A111 WebUI Launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Settings file found, loading
 →   Updating Settings File  ✓
 i   Launcher Version 1.7.0
 i   No Launcher launch options
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Checking requirements :
 i   Python 3.10.10150.1013 found in registry:  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0
 !   This is not the recommended version of Python and will probably cause errors
 i   Clearing PATH of any mention of Python
 →   Adding python 3.10 to path  ✓
 i   Git found and already in PATH:  C:\Program Files\Git\cmd\git.exe
 i   Automatic1111 SD WebUI found:  C:\tools\A1111 Web UI Autoinstaller\stable-diffusion-webui
 i   One or more checkpoint models were found
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading Complete, opening launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   No arguments set
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Webui
 ✓   Done
 i   There is no extension in the extensions folder
 i   No arguments set
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  WEBUI LAUNCHING VIA EMS LAUNCHER, EXIT THIS WINDOW TO STOP THE WEBUI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 !   Any error happening after 'commit hash : XXXX' is not related to the launcher. Please report them on Automatic1111's github instead :
 ☁   https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/new/choose
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cancel
Couldn't launch python

exit code: 5

stderr:
Access denied

Launch unsuccessful. Exiting.

**Comment by onizukadesu** [comment]
I have the exact same problem and can't find a solution.

**Comment by LordOfTheSnow** [comment]
Well maybe you should improve your installer so that itworks with a valid Windows Python installation. Using a launcher like yours only makes sense if you don't have to install the rest manually or even remove something that worked without problems with any other Python project.

**Comment by Mozoloa** [comment]
This is not a valid python installation, as you need 3.10.6 not 3.10.6

**Comment by turpie** [comment]
If A111 is going to be fussy about which version of Python it uses, why can't it bundle the one it needs like Easy Diffusion does?

**Comment by Mozoloa** [comment]
> If A111 is going to be fussy about which version of Python it uses, why can't it bundle the one it needs like Easy Diffusion does?

That's something to debate on his repo, not here, that's merely an unofficial launcher launcher
