### ISSUE TITLE
Python version warning stickiness

### ISSUE THREAD

**Issue by Void2258** [EmpireMediaScience/A1111-Web-UI-Installer#60]
When starting, if the python version is not identical to the one expected, it pops a warning box. For minor updates (ie 3.10.X) there shouldn't be an issue and many people may need to stay up to date on python version changes for other reasons, so freezing it just for this program is not always viable. More major updates (3.10->3.11) have more of a potential to cause issues and definitely should be called out. Having seen this popup, if something goes wrong, you know what happened and can back up, or proceed knowing there is no issue. 

However, this box will continue to pop up every single time you open the launcher. Please have this notification only once when the version is first changed, then skip until the next time the python version changes. It already checks the version number, so it just needs to remember that it already warned for this version.

**Comment by Mozoloa** [comment]
"it just needs to remember" is not as straight forward as you think, but which pop up are you talking about ?

**Comment by Void2258** [comment]
![image](https://user-images.githubusercontent.com/6126362/225649079-ee2cfb5a-3c16-41bf-9efe-b571cec413e7.png)
 This one.
