### ISSUE TITLE
[Enhancement]: Move to new drive/folder.  This would be really cool.  

### ISSUE THREAD

**Issue by Elconite** [EmpireMediaScience/A1111-Web-UI-Installer#63]
### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No problem besides having a complex install on a slower than optimal harddrive and needing to move it.  I'm very technically savvy yet not very versed on some of these particular things.  

### What's the feature

It would be nice to have the ability to move the Auto1111 install and assets to another drive location.  

### How would it work ?

1. Go to .... initial menu 
2. Press .... check box to move to new location
3. ... enter new location and press a new "execute" button to assert that function

### Additional information, context and logs

You're awesome.  Thank you.

**Comment by Mozoloa** [comment]
I'll try to make it super portable in V2, but you should already be able to move the folder wherever you want, and just change the path in the target of the shortcut
