### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kukuli82** [EmpireMediaScience/A1111-Web-UI-Installer#68]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part

### Did this problem occur before the "commit hash:" line in the log ?

- [X] I swear that this problem occurred before the "commit hash:" line in the log, and that if it has instead occured after, I owe the devs a $10.000 donation.

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

Stable diffusion model failed to load, exiting
![360截图20230405111800251](https://user-images.githubusercontent.com/118684201/229972788-4fdf0094-4d83-438a-9a39-545059cc5fcd.jpg)

### Steps to reproduce the problem

1. run A1111 WebUI (Pin to Taskbar)
2. Press "launch webui"

### What should have happened?

go web

### Version of the Installer/Launcher where the problem happens

win11 build

**Comment by Mozoloa** [comment]
your model si probably corrupted, also thanks for the 10K donation, very generous, here's my paypal : [https://paypal.me/leomozoloa](https://paypal.me/leomozoloa)
