### ISSUE TITLE
Error - Consuming HD Space

### ISSUE THREAD

**Issue by D-Impaller** [EmpireMediaScience/A1111-Web-UI-Installer#7]
Hi! First of all, I want to congratulate you for your awesome work! Congratulations!

Unfortunately, when installing, something went wrong and somehow my HD that had 200GB+, now has only 17GB.
I believe that I is due to me trying to install after the error (the page closes, so I can't see the actual error).

How can I erase/uninstall all of the thins that are ocupying my HD space, fix the problem and the reinstall it again?

Can you please help me?

Thanks in advance!

**Comment by Mozoloa** [comment]
This is not related to this installer, you should ask in [the Webui repo itself ](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/new/choose)
