### ISSUE TITLE
[Enhancement]: Allow installation of other forks

### ISSUE THREAD

**Issue by rexelbartolome** [EmpireMediaScience/A1111-Web-UI-Installer#73]
### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

There's been some talk that in the community that we need to move on from relying so much on A1111 because he isn't as open minded about the direction/improvement of the webui, maybe slower updates, and he also refuses to accept help. So people have started forks that are arguably better than his main branch.

### What's the feature

Allow installation of forks, maybe just a select few. Maybe you could also add installing other UI's like EasyDiffusion or whatever but that's not really what I'm going for.

### How would it work ?

Have a drop down of what should be installed, selecting either the main A1111 branch or other forks.

### Additional information, context and logs

This seems to be a popular fork that people have been recommending: https://github.com/vladmandic/automatic

**Comment by Mozoloa** [comment]
Hello sorry for the delay, I've seen some cool forks recently, and if they work the same way regarding command line arguments I'm not sure why I wouldn't implement a drop down for the UI you want to run (and why not both at the same time btw)

**Comment by JaysonPhoenix** [comment]
came to kinda ask for the same, would want this to work with https://github.com/anapnoe/stable-diffusion-webui-ux since i wouldnt wanna use any ui without such a launcher anymore keeping everything up to date and running smooth, besides the ease of the installation which enables me to get friends to use stable diffusion who wouldnt touch it otherwise. so please add such an option to chose which ui to install/boot-up.

**Comment by rexelbartolome** [comment]
IKR, telling my friends to install stable diffusion knowing that they might come across some obscure python error while following installation steps is a big reason why I don't do it as much 😔
