### ISSUE TITLE
v1.3.1 Does not launch browser.

### ISSUE THREAD

**Issue by akalink** [EmpireMediaScience/A1111-Web-UI-Installer#8]
After CMD is run, it prompts you to click any key. After you press a key to continue, the cmd closes and no webpages is opened.

**Comment by Mozoloa** [comment]
Hello, i'm going to need more info and screenshots about all this, and exactly how to reproduce the problem, this happens sometimes when you have no checkpoints models in your model folder, and this is unrelated to the installer

**Comment by akalink** [comment]
Please note I installed the newest release (1.3.2 as typing this) and now it works fine. I followed the install guide, started with a install of git and python, when finished selected clean install, and install SD checkpoint. When Automatic1111Webui popped up I launched it, waited for the cmd to finish installing, hit enter to continue.

**Comment by Mozoloa** [comment]
Good, this release didn't change anything regarding the installation tho so you probably missed something in the readme the first time
