### ISSUE TITLE
i am not able to launch A1111 WebUI, i keep getting this error[Bug]: RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

### ISSUE THREAD

**Issue by Fresco-11** [EmpireMediaScience/A1111-Web-UI-Installer#88]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part

### Did this problem occur before the "commit hash:" line in the log ?

- [X] I swear that this problem occurred before the "commit hash:" line in the log, and that if it has instead occured after, I owe the devs a $10.000 donation.

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

i am not able to launch A1111 WebUI, i keep getting this error[Bug]: RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check.
![Screenshot 2023-07-06 002621](https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/assets/138732914/7c654a01-2587-47bf-aa62-2bde59e1b1b5)

### Steps to reproduce the problem

1. Go to webui-user batch file

### What should have happened?

The link to launch the A1111 WebUI should have come up

### Version of the Installer/Launcher where the problem happens

V1.7.0

**Comment by Mozoloa** [comment]
Thanks for the 10K$

**Comment by Fresco-11** [comment]
How do I fix the issue?
