### ISSUE TITLE
How do you compile the source code? is that automatic? how can we ensure the released exe is authentic

### ISSUE THREAD

**Issue by FurkanGozukara** [EmpireMediaScience/A1111-Web-UI-Installer#9]
First of all ty so much for this tool
I am going to make a tutorial video for that

But I just want to be sure that the released exe is compiled through the source code without any changes

Are there any way to verify that?

**Comment by Mozoloa** [comment]
Hello, as stated in the readme, this is compiled with Advanced Installer (19.2 iirc), so if someone has a similar version, he could just git clone, run the .aip and build.

**Comment by FurkanGozukara** [comment]
> Hello, as stated in the readme, this is compiled with Advanced Installer (19.2 iirc), so if someone has a similar version, he could just git clone, run the .aip and build.

thanks. so would hashes match?

**Comment by Mozoloa** [comment]
I don't see why not, unless there is some metadata difference because of the date. We should try it tbh

**Comment by FurkanGozukara** [comment]
> I don't see why not, unless there is some metadata difference because of the date. We should try it tbh

getting error wit 20.2

will try to find 19.2 to compare

![image](https://user-images.githubusercontent.com/19240467/208742271-d26911b2-e56e-4e50-97c8-f5d074266ad3.png)

**Comment by Mozoloa** [comment]
Check this out, apparently it's just the certificate I used to sign the installer (whatever that means, you should be able to select another one)
<img width="926" alt="Screenshot 2022-12-20 at 19 44 47" src="https://user-images.githubusercontent.com/20817233/208742782-26c61089-6528-4c94-a54a-f688473ce056.png">

**Comment by FurkanGozukara** [comment]
> Check this out, apparently it's just the certificate I used to sign the installer (whatever that means, you should be able to select another one) <img alt="Screenshot 2022-12-20 at 19 44 47" width="926" src="https://user-images.githubusercontent.com/20817233/208742782-26c61089-6528-4c94-a54a-f688473ce056.png">

thanks

i have disabled sign in from here

![image](https://user-images.githubusercontent.com/19240467/208743402-87962ab0-445a-4582-8784-74e4b2477f78.png)


and compiled

this is the output i got

![image](https://user-images.githubusercontent.com/19240467/208743441-da4bd982-212a-4edf-9339-5bac5d5203c2.png)

it doesnt match because if you have signed that would make difference

although the size is same

**Comment by Mozoloa** [comment]
I have no idea what those do tbh, I don't think signing is required, I probably just turned it on to avoid people having warning from windows, but this doesn't seem to change anything lmao. If you discover better ways of doing things, don't hesitate to Pull Request

**Comment by FurkanGozukara** [comment]
can you also publish unsigned release. in that case i think we could get exactly same hash

**Comment by Mozoloa** [comment]
Now I see that you're building 1.3 but I think we were at 1.3.1 or something, I may have forgotten to update the installer, I'll have a look

**Comment by Mozoloa** [comment]
Alright check this out : https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/releases/tag/V1.3.2

Git pull to get the last .aip

**Comment by FurkanGozukara** [comment]
> Alright check this out : https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/releases/tag/V1.3.2
> 
> Git pull to get the last .aip

still got different hash. i dont know why. but here the file sizes

my compile : 4.52 MB (4,748,022 bytes)
your exe : 4.52 MB (4,748,214 bytes)

now almost exactly same size 

I opened 1.9.2 and built like this. by the way my version is trial. it could be embedding some trial info etc not sure

![image](https://user-images.githubusercontent.com/19240467/208763087-cbc36606-be07-4dc2-88d7-f2eeaf486fd3.png)

**Comment by Mozoloa** [comment]
That could be it, or a time difference. If someone else can get the same hash as you doing the same thing, and that the installer still works properly, we can use this crowdsourced exe as the release

**Comment by FurkanGozukara** [comment]
> That could be it, or a time difference. If someone else can get the same hash as you doing the same thing, and that the installer still works properly, we can use this crowdsourced exe as the release

just leaving as reference if anyone else tries. version 19.2 trial

md5 : 7a4e15be5a238f17451636bab45fcdea
sha1 : bb599eb85d520126d1579958569db95127bc4a77

**Comment by Mozoloa** [comment]
Have you tried comparing the two .aip files ? afaik they're just xmls, if they're the same they shouldn't be producing different builds

**Comment by Mozoloa** [comment]
I'll try to use 20.2 trial asap and we'll compare

**Comment by FurkanGozukara** [comment]
> I'll try to use 20.2 trial asap and we'll compare

Sure I have that too. I will also post back when I return home

**Comment by FurkanGozukara** [comment]
@Mozoloa  I just used the installer compiled by me by the trial version of advanced installer and during the installation it alerted a message said this exe was compiled with trial version. this explains hash difference

**Comment by Mozoloa** [comment]
So have you tried with a complete version ?

**Comment by FurkanGozukara** [comment]
> So have you tried with a complete version ?

i dont have paid version unfortunately only trial

**Comment by FurkanGozukara** [comment]
@Mozoloa 

 I have prepared the tutorial for this app  :) 
I hope you can add it to the readme and also to the topic on reddit https://www.reddit.com/r/StableDiffusion/comments/zpansd/automatic1111s_stable_diffusion_webui_easy/

thank you so much for this great app for free

https://www.youtube.com/watch?v=AZg6vzWHOTA

**Comment by Mozoloa** [comment]
Hey, I'll see whenever I can ! I'll close this issue as you showed that even a trial of AI allowed you to perfectly build and install the software, so if people don't trust my exe they can just compile it themselves !
